# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your Awesome Title
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
facebook:
 app_id: 1234
 publisher: 1234
 admins: 1234
 logo: "" # URL to a site-wide logo (e.g., /assets/your-company-logo.png)

social:
  name: #Ben Banter
  links:
    #- https://twitter.com/BenBanter
    #- https://www.facebook.com/ben.banter
    #- https://www.linkedin.com/in/BenBanter
    #- https://plus.google.com/+BenBanter
    #- https://github.com/benbanter
    #- https://keybase.io/benbanter

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234

# Google services
google_analytics: UA—XXXXXXXX-X
    
# Build settings
markdown: kramdown
theme: 
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji 
  - jekyll-pwa-plugin

  
#jekyll-mentions:
#  base_url: https://twitter.com

tag_page_layout: tags
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

ignored_tags: [blog]

tag_page_data:
  sitemap: false

pwa:
sw_src_filepath: service-worker.js # Optional
sw_dest_filename: service-worker.js # Optional
dest_js_directory: assets/js # Required
precache_recent_posts_num: 5 # Optional
precache_glob_directory: / # Optional
precache_glob_patterns: # Optional
  - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
  - index.html
precache_glob_ignores: # Optional
  - sw-register.js
  - "fonts/**/*"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
